name: Ocaml action

on:
  - push
  - workflow_dispatch

jobs:
  testing:
    name: testing
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"
          allow-prerelease-opam: true
          dune-cache: true

      - run: opam exec -- dune build
